document.addEventListener("DOMContentLoaded", function() {
    const translations = {
        en: {
            navAbout: "About",
            navServices: "Services",
            navExperience: "Experience",
            navTestimonials: "Testimonials",
            navPortfolio: "Portfolio",
            navGetInTouch: "Get in touch",
            mNavAbout: "About",
            mNavServices: "Services",
            mNavExperience: "Experience",
            mNavTestimonials: "Testimonials",
            mNavPortfolio: "Portfolio",
            mNavGetInTouch: "Get in touch",
            heroDragHint: "Drag to explore",
            skillsTitle: "Skills & Expertise",
            skillsSub: "A snapshot of the capabilities I bring to safety and people development.",
            skill1: "HSE Training & Induction",
            skill2: "Training Needs Analysis",
            skill3: "Recruitment & Talent Management",
            skill4: "LMS & Digital Learning",
            skill5: "HRIS / SAP ERP",
            skill6: "QCC & Six Sigma",
            impactTitle: "Impact in 3D",
            impactSub: "Drag the chart to rotate it and hover the bars to explore the numbers behind the work.",
            legend1: "Competency Gap Reduction",
            legend2: "Fuel Savings (HDT)",
            legend3: "YLP Graduates",
            legend4: "Training Satisfaction",
            heroBgText: "SAFETY",
            heroTitle: "I'M<br>AHMAD",
            heroBtnCv: "Download CV",
            heroBtnDiscuss: "Let's Discuss",
            heroGreeting: "Hello, I'm Ahmad Faqih, a proactive, data-driven Safety and People Development Specialist with over 4 years of experience.",
            heroFollow: "Follow Me",
            heroSubGreeting: "I design rigorous competency frameworks, automate workflows, and develop impactful dashboards.",
            heroRole: "SAFETY & PEOPLE<br>DEVELOPMENT",
            aboutTitle: "Driving a Culture of Safety & Talent Growth.",
            aboutDesc: "A proactive, data-driven, and highly innovative Safety and People Development Specialist with over 4 years of experience in the mining and heavy equipment sectors. Adept at improving organizational performance through the seamless integration of modern digital systems and strategic talent development. Backed by pivotal BNSP certifications including AK3 Umum, Operational Supervisor (POP), and Training of Trainer (TOT) KKNI Level 4, bringing a unique, high-impact blend of stringent safety operations, human capital transformation, and technological efficiency.",
            whyHireTitle: "Why Hire Me?",
            whyHireSubTitle: "A unique blend of safety expertise, people development skills, and system digitalization.",
            whyHireCard1Title: "Safety Culture Driver",
            whyHireCard1Desc: "Expert in implementing SMKP standards and developing engaging HSE programs that reduce incidents and build a proactive safety-first mindset across all operational levels.",
            whyHireCard2Title: "Proven Talent Developer",
            whyHireCard2Desc: "Successfully designed and launched high-impact programs like the Young Leadership Program (YLP) to nurture future leaders and close critical competency gaps.",
            whyHireCard3Title: "HR Digitalization Expert",
            whyHireCard3Desc: "Skilled in building and deploying digital HR tools, including Learning Management Systems (LMS), to streamline processes and enhance training effectiveness.",
            servicesTitle: "Services & Expertise",
            servicesSubTitle: "Focused on human resource development and safety systems to achieve operational excellence.",
            serviceCard1Title: "HSE Training & Induction",
            serviceCard1Desc: "Developing internal training modules (JSA, HIRA-DC) and SMKP-based safety inductions.",
            serviceCard2Title: "People Development",
            serviceCard2Desc: "Designing and executing talent management, career development, and leadership programs.",
            serviceCard3Title: "System Development",
            serviceCard3Desc: "Building web-based LMS, competency frameworks, and deploying HR systems (SAP/ERP).",
            serviceCard4Title: "HR & Recruitment",
            serviceCard4Desc: "Managing end-to-end recruitment, onboarding, and HR administration for optimal performance.",
            experienceTitle: "My Career Journey",
            experienceSubTitle: "A detailed history of my professional roles and accomplishments.",
            exp1Title: "Foreman - System, Compliance & Training, Promotion (HSE)",
            exp1Company: "PT Ganda Alam Makmur",
            exp1Date: "Dec 2024 - Present",
            exp1Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Developed and delivered core modules (JSA, HIRA-DC, Investigation) and led employee inductions aligned with SMKP standards.</li><li>Coordinated internal SMKP audits and designed mandatory safety training matrices.</li><li>Introduced simulation-based field assessments for supervisors.</li><li><strong>Achievement:</strong> Reduced Basic Safety competency gaps from 90% to 40% within 6 months.</li><li><strong>Achievement:</strong> Designed a Practical Field Test Area and developed impactful safety dashboards.</li></ul>`,
            exp2Title: "Supervisor - People Development (HRGA)",
            exp2Company: "PT Manoor Bulatn Lestari",
            exp2Date: "May 2024 - Dec 2024",
            exp2Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Managed end-to-end hiring and staffing forecasts while digitalizing recruitment workflows.</li><li>Conducted Training Needs Analysis (TNA) and delivered tailored programs to bridge skill gaps.</li><li><strong>Achievement:</strong> Automated recruitment and onboarding, significantly improving hiring efficiency.</li><li><strong>Achievement:</strong> Launched the "YLP" for top-tier graduates, integrating QCC projects.</li><li><strong>Achievement:</strong> Standardized PKWT/PKWTT contracts for Fresh Graduates, ensuring 100% legal compliance.</li></ul>`,
            exp3Title: "Group Leader - System & Training, People Development (HRGA)",
            exp3Company: "PT Putra Perkasa Abadi",
            exp3Date: "Mar 2022 - Dec 2023",
            exp3Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Built a web-based Learning Management System (LMS) with modules and assessments.</li><li>Led internal QCC training and managed all logistics, vendor selection, and certification.</li><li>Formulated competency frameworks and managed orientation programs for fresh graduates.</li><li>Managed TNA, training investments, and SAP/HRIS data entry for new hires.</li></ul>`,
            testimonialsTitle: "What My Colleagues Say",
            testimonialsSubTitle: "Feedback from professionals I've worked with.",
            testimonial1Text: `"Ahmad is a game-changer. His ability to translate complex safety regulations into practical, engaging training modules significantly improved our team's safety awareness and performance."`,
            testimonial1Name: "Jane Doe",
            testimonial1Role: "Former Manager, PT Ganda Alam Makmur",
            testimonial2Text: `"The Young Leadership Program Ahmad launched was transformative. He has a rare talent for identifying potential and building systems that foster growth and leadership."`,
            testimonial2Name: "John Smith",
            testimonial2Role: "HR Director, PT Manoor Bulatn Lestari",
            portfolioTitle: "Featured Initiatives & Projects",
            portfolioSubTitle: "Key initiatives to improve safety, competence, and efficiency.",
            project1Title: "Young Leadership Program (YLP)",
            project1Category: "Talent & Leadership Development",
            project2Title: "LV Practical Field Test Area",
            project2Category: "Safety Initiative",
            educationTitle: "Education",
            educationDegree: "Bachelor's Degree in Management",
            educationUniversity: "Islamic University of Indonesia",
            educationDate: "2017 - 2021",
            educationDesc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Specialized in Finance/Risk Management, HR, and Operations.</li><li>Won 1st place in the faculty's Business Model Canvas competition.</li></ul>`,
            certsTitle: "Professional Certifications",
            cert1Title: "AK3 Umum",
            cert1Issuer: "BNSP (02/2026 - 02/2029)",
            cert2Title: "First Line Operational Supervisor (POP)",
            cert2Issuer: "BNSP (04/2024 - 04/2027)",
            cert3Title: "Trainer (TOT) KKNI Level 4",
            cert3Issuer: "BNSP (09/2023 - 09/2028)",
            cert4Title: "SMKP Implementation",
            cert4Issuer: "PPSDM (03/2023 - 03/2028)",
            cert5Title: "Human Resources Staff",
            cert5Issuer: "BNSP (11/2021 - 11/2024)",
            contactTitle: "Let's Build Something Amazing Together",
            contactLocationNote: "Based in Semarang, Indonesia — open to opportunities worldwide.",
            contactBtn: "Start a Conversation",
            footerRole: "HSE & Training Professional",
            footerLinksTitle: "Quick Links",
            footerLinkAbout: "About",
            footerLinkExperience: "Experience",
            footerLinkPortfolio: "Portfolio",
            footerLinkContact: "Contact",
            footerContactTitle: "Contact Me",
            footerContactEmail: "Email: ahmadfaqihdidin@gmail.com",
            footerContactPhone: "Phone: +62 821 4742 2821",
            footerContactLocation: "Location: Semarang, Indonesia",
            footerMadeWith: "Made with 💕 by Istri Cantikku ( Mimma M A).."
        },
        id: {
            navAbout: "Tentang",
            navServices: "Layanan",
            navExperience: "Pengalaman",
            navTestimonials: "Testimoni",
            navPortfolio: "Portofolio",
            navGetInTouch: "Hubungi Saya",
            mNavAbout: "Tentang",
            mNavServices: "Layanan",
            mNavExperience: "Pengalaman",
            mNavTestimonials: "Testimoni",
            mNavPortfolio: "Portofolio",
            mNavGetInTouch: "Hubungi Saya",
            heroDragHint: "Seret untuk menjelajah",
            skillsTitle: "Keahlian & Kompetensi",
            skillsSub: "Sekilas kemampuan yang saya bawa untuk keselamatan dan pengembangan manusia.",
            skill1: "Pelatihan & Induksi K3",
            skill2: "Analisis Kebutuhan Pelatihan",
            skill3: "Rekrutmen & Manajemen Talenta",
            skill4: "LMS & Pembelajaran Digital",
            skill5: "HRIS / SAP ERP",
            skill6: "GKM & Six Sigma",
            impactTitle: "Dampak dalam 3D",
            impactSub: "Seret grafik untuk memutarnya dan arahkan kursor ke batang untuk melihat angka di baliknya.",
            legend1: "Penurunan Kesenjangan Kompetensi",
            legend2: "Penghematan BBM (HDT)",
            legend3: "Lulusan YLP",
            legend4: "Kepuasan Pelatihan",
            heroBgText: "K3",
            heroTitle: "SAYA<br>AHMAD",
            heroBtnCv: "Unduh CV",
            heroBtnDiscuss: "Mari Diskusi",
            heroGreeting: "Halo, saya Ahmad Faqih, Spesialis K3 & Pengembangan SDM yang proaktif dan berbasis data dengan pengalaman lebih dari 4 tahun.",
            heroFollow: "Ikuti Saya",
            heroSubGreeting: "Saya merancang kerangka kompetensi, mengotomatiskan alur kerja, dan mengembangkan dasbor yang berdampak.",
            heroRole: "PENGEMBANGAN<br>K3 & SDM",
            aboutTitle: "Mendorong Budaya Keselamatan & Pertumbuhan Bakat.",
            aboutDesc: "Spesialis K3 dan Pengembangan SDM yang proaktif, berbasis data, dan sangat inovatif dengan pengalaman lebih dari 4 tahun di sektor pertambangan dan alat berat. Mahir dalam meningkatkan kinerja organisasi melalui integrasi sistem digital modern dan pengembangan bakat strategis. Didukung oleh sertifikasi BNSP penting termasuk AK3 Umum, Pengawas Operasional Pertama (POP), dan Training of Trainer (TOT) KKNI Level 4, membawa perpaduan berdampak tinggi dari operasi keselamatan yang ketat, transformasi modal manusia, dan efisiensi teknologi.",
            whyHireTitle: "Mengapa Merekrut Saya?",
            whyHireSubTitle: "Perpaduan unik antara keahlian keselamatan, keterampilan pengembangan sumber daya manusia, dan digitalisasi sistem.",
            whyHireCard1Title: "Pendorong Budaya Keselamatan",
            whyHireCard1Desc: "Ahli dalam menerapkan standar SMKP dan mengembangkan program K3 yang menarik untuk mengurangi insiden dan membangun pola pikir proaktif yang mengutamakan keselamatan di semua tingkat operasional.",
            whyHireCard2Title: "Pengembang Talenta Terbukti",
            whyHireCard2Desc: "Berhasil merancang dan meluncurkan program berdampak tinggi seperti Program Kepemimpinan Muda (YLP) untuk membina pemimpin masa depan dan menutup kesenjangan kompetensi kritis.",
            whyHireCard3Title: "Pakar Digitalisasi HR",
            whyHireCard3Desc: "Terampil dalam membangun dan menerapkan alat HR digital, termasuk Learning Management Systems (LMS), untuk menyederhanakan proses dan meningkatkan efektivitas pelatihan.",
            servicesTitle: "Layanan & Keahlian",
            servicesSubTitle: "Berfokus pada pengembangan sumber daya manusia dan sistem keselamatan untuk mencapai keunggulan operasional.",
            serviceCard1Title: "Pelatihan & Induksi K3",
            serviceCard1Desc: "Mengembangkan modul pelatihan internal (JSA, HIRA-DC) dan induksi keselamatan berbasis SMKP.",
            serviceCard2Title: "Pengembangan SDM",
            serviceCard2Desc: "Merancang dan melaksanakan manajemen talenta, pengembangan karir, dan program kepemimpinan.",
            serviceCard3Title: "Pengembangan Sistem",
            serviceCard3Desc: "Membangun LMS berbasis web, kerangka kerja kompetensi, dan menerapkan sistem HR (SAP/ERP).",
            serviceCard4Title: "HR & Perekrutan",
            serviceCard4Desc: "Mengelola rekrutmen ujung-ke-ujung, orientasi, dan administrasi HR untuk kinerja optimal.",
            experienceTitle: "Perjalanan Karir Saya",
            experienceSubTitle: "Riwayat terperinci tentang peran dan pencapaian profesional saya.",
            exp1Title: "Foreman - Sistem, Kepatuhan & Pelatihan, Promosi (K3)",
            exp1Company: "PT Ganda Alam Makmur",
            exp1Date: "Des 2024 - Sekarang",
            exp1Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Mengembangkan dan memberikan modul inti (JSA, HIRA-DC, Investigasi) dan memimpin induksi selaras dengan standar SMKP.</li><li>Mengoordinasikan audit internal SMKP dan merancang matriks pelatihan wajib.</li><li>Memperkenalkan penilaian lapangan berbasis simulasi untuk pengawas.</li><li><strong>Pencapaian:</strong> Mengurangi kesenjangan kompetensi Keselamatan Dasar dari 90% menjadi 40% dalam 6 bulan.</li><li><strong>Pencapaian:</strong> Merancang Area Uji Lapangan Praktis dan mengembangkan dasbor keselamatan yang berdampak.</li></ul>`,
            exp2Title: "Supervisor - Pengembangan SDM (HRGA)",
            exp2Company: "PT Manoor Bulatn Lestari",
            exp2Date: "Mei 2024 - Des 2024",
            exp2Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Mengelola rekrutmen ujung-ke-ujung dan peramalan kepegawaian sambil mendigitalisasi alur kerja.</li><li>Melakukan Analisis Kebutuhan Pelatihan (TNA) dan memberikan program yang disesuaikan.</li><li><strong>Pencapaian:</strong> Mengotomatiskan perekrutan dan orientasi, secara signifikan meningkatkan efisiensi.</li><li><strong>Pencapaian:</strong> Meluncurkan "YLP" untuk lulusan terbaik, mengintegrasikan proyek GKM.</li><li><strong>Pencapaian:</strong> Menstandarisasi kontrak PKWT/PKWTT untuk Fresh Graduate sesuai kepatuhan hukum.</li></ul>`,
            exp3Title: "Pemimpin Grup - Sistem & Pelatihan, Pengembangan SDM (HRGA)",
            exp3Company: "PT Putra Perkasa Abadi",
            exp3Date: "Mar 2022 - Des 2023",
            exp3Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Membangun Sistem Manajemen Pembelajaran (LMS) berbasis web dengan modul dan penilaian.</li><li>Memimpin pelatihan GKM internal dan mengelola logistik, pemilihan vendor, dan sertifikasi.</li><li>Merumuskan kerangka kerja kompetensi dan mengelola program orientasi untuk lulusan baru.</li><li>Mengelola TNA, investasi pelatihan, dan entri data SAP/HRIS untuk karyawan baru.</li></ul>`,
            testimonialsTitle: "Apa Kata Rekan Kerja Saya",
            testimonialsSubTitle: "Umpan balik dari para profesional yang pernah bekerja dengan saya.",
            testimonial1Text: `"Ahmad adalah seorang pengubah permainan. Kemampuannya untuk menerjemahkan peraturan keselamatan yang kompleks menjadi modul pelatihan yang praktis dan menarik secara signifikan meningkatkan kesadaran dan kinerja keselamatan tim kami."`,
            testimonial1Name: "Jane Doe",
            testimonial1Role: "Mantan Manajer, PT Ganda Alam Makmur",
            testimonial2Text: `"Program Kepemimpinan Muda yang diluncurkan Ahmad sangat transformatif. Dia memiliki bakat langka untuk mengidentifikasi potensi dan membangun sistem yang mendorong pertumbuhan dan kepemimpinan."`,
            testimonial2Name: "John Smith",
            testimonial2Role: "Direktur HR, PT Manoor Bulatn Lestari",
            portfolioTitle: "Inisiatif & Proyek Unggulan",
            portfolioSubTitle: "Inisiatif kunci untuk meningkatkan keselamatan, kompetensi, dan efisiensi.",
            project1Title: "Program Kepemimpinan Muda (YLP)",
            project1Category: "Pengembangan Bakat & Kepemimpinan",
            project2Title: "Area Uji Lapangan Praktis LV",
            project2Category: "Inisiatif Keselamatan",
            educationTitle: "Pendidikan",
            educationDegree: "Sarjana Manajemen",
            educationUniversity: "Universitas Islam Indonesia",
            educationDate: "2017 - 2021",
            educationDesc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Spesialisasi di bidang Manajemen Keuangan/Risiko, SDM, dan Operasi.</li><li>Juara 1 dalam kompetisi Business Model Canvas fakultas.</li></ul>`,
            certsTitle: "Sertifikasi Profesional",
            cert1Title: "AK3 Umum",
            cert1Issuer: "BNSP (02/2026 - 02/2029)",
            cert2Title: "Pengawas Operasional Pertama (POP)",
            cert2Issuer: "BNSP (04/2024 - 04/2027)",
            cert3Title: "Pelatih (TOT) KKNI Level 4",
            cert3Issuer: "BNSP (09/2023 - 09/2028)",
            cert4Title: "Implementasi SMKP",
            cert4Issuer: "PPSDM (03/2023 - 03/2028)",
            cert5Title: "Staf Sumber Daya Manusia",
            cert5Issuer: "BNSP (11/2021 - 11/2024)",
            contactTitle: "Mari Bangun Sesuatu yang Luar Biasa Bersama",
            contactLocationNote: "Berbasis di Semarang, Indonesia — terbuka untuk peluang di seluruh dunia.",
            contactBtn: "Mulai Percakapan",
            footerRole: "Profesional K3 & Pelatihan",
            footerLinksTitle: "Tautan Cepat",
            footerLinkAbout: "Tentang",
            footerLinkExperience: "Pengalaman",
            footerLinkPortfolio: "Portofolio",
            footerLinkContact: "Kontak",
            footerContactTitle: "Hubungi Saya",
            footerContactEmail: "Email: ahmadfaqihdidin@gmail.com",
            footerContactPhone: "Telepon: +62 821 4742 2821",
            footerContactLocation: "Lokasi: Semarang, Indonesia",
            footerMadeWith: "Made with 💕 by Istri Cantikku ( Mimma M A)."
        }
    };

    window.currentLang = 'en'; // Default language, accessible globally

    function setLanguage(lang) {
        document.documentElement.lang = lang;
        document.querySelectorAll('[data-lang-key]').forEach(el => {
            const key = el.dataset.langKey;
            if (translations[lang] && translations[lang][key]) {
                el.innerHTML = translations[lang][key];
            }
        });
        window.currentLang = lang;
        // Dispatch on both targets so listeners attached to window or document both receive it
        window.dispatchEvent(new CustomEvent('langchange', { detail: { lang } }));
        document.dispatchEvent(new CustomEvent('langchange', { detail: { lang } }));
        document.getElementById('translate-button').textContent = lang === 'en' ? 'ID' : 'EN';
        document.getElementById('translate-button-mobile').textContent = lang === 'en' ? 'ID' : 'EN';
    }

    function handleTranslateClick() {
        const newLang = window.currentLang === 'en' ? 'id' : 'en';
        setLanguage(newLang);
    }

    document.getElementById('translate-button').addEventListener('click', handleTranslateClick);
    document.getElementById('translate-button-mobile').addEventListener('click', handleTranslateClick);

    // Set initial language
    setLanguage('en');
});
