document.addEventListener("DOMContentLoaded", function() {
    const translations = {
        en: {
            navAbout: "About",
            navServices: "Services",
            navExperience: "Experience",
            navTestimonials: "Testimonials",
            navPortfolio: "Portfolio",
            navGetInTouch: "Get in touch",
            mNavAbout: "About",
            mNavServices: "Services",
            mNavExperience: "Experience",
            mNavTestimonials: "Testimonials",
            mNavPortfolio: "Portfolio",
            mNavGetInTouch: "Get in touch",
            heroBgText: "SAFETY",
            heroTitle: "I'M<br>AHMAD",
            heroBtnCv: "Download CV",
            heroBtnDiscuss: "Let's Discuss",
            heroGreeting: "Hello, I'm Ahmad Faqih, an HSE & Training Professional passionate about creating meaningful safety cultures.",
            heroFollow: "Follow Me",
            heroSubGreeting: "I design & implement user-centric safety systems and training programs.",
            heroRole: "HSE & TRAINING<br>PROFESSIONAL",
            aboutTitle: "Driving a Culture of Safety & Talent Growth.",
            aboutDesc: "A dedicated HR and Training professional with a strong background in safety system training and promotion within the coal mining industry. I specialize in developing and delivering safety-focused training programs that support Good Mining Practice and improve operational efficiency. Skilled in onboarding processes, competency development, internal SMKP audits, and digital HR tools such as LMS, Google Sheets, Power BI, and PHP Laravel. Proven ability to build safety awareness, support workforce development, and optimize HR systems to drive performance and compliance.",
            whyHireTitle: "Why Hire Me?",
            whyHireSubTitle: "A unique blend of safety expertise, people development skills, and system digitalization.",
            whyHireCard1Title: "Safety Culture Driver",
            whyHireCard1Desc: "Expert in implementing SMKP standards and developing engaging HSE programs that reduce incidents and build a proactive safety-first mindset across all operational levels.",
            whyHireCard2Title: "Proven Talent Developer",
            whyHireCard2Desc: "Successfully designed and launched high-impact programs like the Young Leadership Program (YLP) to nurture future leaders and close critical competency gaps.",
            whyHireCard3Title: "HR Digitalization Expert",
            whyHireCard3Desc: "Skilled in building and deploying digital HR tools, including Learning Management Systems (LMS), to streamline processes and enhance training effectiveness.",
            servicesTitle: "Services & Expertise",
            servicesSubTitle: "Focused on human resource development and safety systems to achieve operational excellence.",
            serviceCard1Title: "HSE Training & Induction",
            serviceCard1Desc: "Developing internal training modules (JSA, HIRA-DC) and SMKP-based safety inductions.",
            serviceCard2Title: "People Development",
            serviceCard2Desc: "Designing and executing talent management, career development, and leadership programs.",
            serviceCard3Title: "System Development",
            serviceCard3Desc: "Building web-based LMS, competency frameworks, and deploying HR systems (SAP/ERP).",
            serviceCard4Title: "HR & Recruitment",
            serviceCard4Desc: "Managing end-to-end recruitment, onboarding, and HR administration for optimal performance.",
            experienceTitle: "My Career Journey",
            experienceSubTitle: "A detailed history of my professional roles and accomplishments.",
            exp1Title: "Health Safety Environment - System, Training & Promotion",
            exp1Company: "PT Ganda Alam Makmur",
            exp1Date: "Dec 2023 - Present",
            exp1Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Developed and delivered internal HSE training modules: JSA, HIRA-DC, Investigation, and Effective Safety Communication.</li><li>Led safety inductions for new employees and contractors, aligned with SMKP standards.</li><li>Coordinated internal audits for SMKP and supported ISO 45001 & 14001 audit readiness.</li><li><strong>Achievement:</strong> Reduced competency gaps from 90% to 40% in 4 months through targeted HSE training.</li><li><strong>Achievement:</strong> Achieved a 15% reduction in fuel consumption for high-capacity dump trucks through ECU remapping.</li></ul>`,
            exp2Title: "Human Resource Supervisor",
            exp2Company: "PT Manoor Bulatn Lestari",
            exp2Date: "Aug 2023 - Dec 2023",
            exp2Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Developed and executed talent management, career development, and change management initiatives.</li><li>Led end-to-end recruitment, from forecasting needs to onboarding, and spearheaded the digitalization of the process.</li><li><strong>Achievement:</strong> Launched the "YLP - Young Leadership Program" for 24 top university graduates.</li><li><strong>Achievement:</strong> Created a Grading Level Structure with standardized salary bands and clear career paths.</li></ul>`,
            exp3Title: "Human Resources",
            exp3Company: "PT Satria Muda Prima",
            exp3Date: "Jan 2023 - Jun 2023",
            exp3Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Led the end-to-end recruitment process, including workforce planning, CV screening, interviews, and psychological assessments.</li><li>Designed and delivered onboarding training programs and performed Training Needs Analysis (TNA).</li><li>Managed compensation, benefits, HR documentation, and employee performance tracking.</li></ul>`,
            exp4Title: "Training, Development & System - Group Leader",
            exp4Company: "PT Putra Perkasa Abadi",
            exp4Date: "Mar 2022 - Nov 2023",
            exp4Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Served as a trainer for internal QCC training and coordinated various training programs.</li><li>Built a web-based Learning Management System (LMS) with modules, user accounts, and assessments.</li><li>Formulated competencies for each position and guided promotion and orientation programs for new workers.</li></ul>`,
            testimonialsTitle: "What My Colleagues Say",
            testimonialsSubTitle: "Feedback from professionals I've worked with.",
            testimonial1Text: `"Ahmad is a game-changer. His ability to translate complex safety regulations into practical, engaging training modules significantly improved our team's safety awareness and performance."`,
            testimonial1Name: "Jane Doe",
            testimonial1Role: "Former Manager, PT Ganda Alam Makmur",
            testimonial2Text: `"The Young Leadership Program Ahmad launched was transformative. He has a rare talent for identifying potential and building systems that foster growth and leadership."`,
            testimonial2Name: "John Smith",
            testimonial2Role: "HR Director, PT Manoor Bulatn Lestari",
            portfolioTitle: "Featured Initiatives & Projects",
            portfolioSubTitle: "Key initiatives to improve safety, competence, and efficiency.",
            project1Title: "Young Leadership Program (YLP)",
            project1Category: "Talent & Leadership Development",
            project2Title: "LV Practical Field Test Area",
            project2Category: "Safety Initiative",
            educationTitle: "Education",
            educationDegree: "Bachelor's Degree in Management",
            educationUniversity: "Islamic University of Indonesia",
            educationDate: "2017 - 2021",
            educationDesc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Specialized in Finance/Risk Management, HR, and Operations.</li><li>Won 1st place in the faculty's Business Model Canvas competition.</li></ul>`,
            certsTitle: "Professional Certifications",
            cert1Title: "Trainer (TOT) KKNI Lvl 4",
            cert1Issuer: "BNSP",
            cert2Title: "First Line Operational Supervisor (POP)",
            cert2Issuer: "BNSP",
            cert3Title: "SMKP Implementation",
            cert3Issuer: "PPSDM",
            cert4Title: "Human Resources Staff",
            cert4Issuer: "BNSP",
            cert5Title: "Six Sigma",
            cert5Issuer: "Online Training",
            contactTitle: "Let's Build Something Amazing Together",
            contactBtn: "Start a Conversation",
            footerRole: "HSE & Training Professional",
            footerLinksTitle: "Quick Links",
            footerLinkAbout: "About",
            footerLinkExperience: "Experience",
            footerLinkPortfolio: "Portfolio",
            footerLinkContact: "Contact",
            footerContactTitle: "Contact Me",
            footerContactEmail: "Email: ahmadfaqihdidin@gmail.com",
            footerContactPhone: "Phone: +62 821 4742 2821",
            footerContactLocation: "Location: Semarang, Indonesia",
            footerMadeWith: "Made with love & code."
        },
        id: {
            navAbout: "Tentang",
            navServices: "Layanan",
            navExperience: "Pengalaman",
            navTestimonials: "Testimoni",
            navPortfolio: "Portofolio",
            navGetInTouch: "Hubungi Saya",
            mNavAbout: "Tentang",
            mNavServices: "Layanan",
            mNavExperience: "Pengalaman",
            mNavTestimonials: "Testimoni",
            mNavPortfolio: "Portofolio",
            mNavGetInTouch: "Hubungi Saya",
            heroBgText: "K3",
            heroTitle: "SAYA<br>AHMAD",
            heroBtnCv: "Unduh CV",
            heroBtnDiscuss: "Mari Diskusi",
            heroGreeting: "Halo, saya Ahmad Faqih, seorang Profesional K3 & Pelatihan yang bersemangat menciptakan budaya keselamatan yang bermakna.",
            heroFollow: "Ikuti Saya",
            heroSubGreeting: "Saya merancang & menerapkan sistem keselamatan dan program pelatihan yang berpusat pada pengguna.",
            heroRole: "PROFESIONAL<br>K3 & PELATIHAN",
            aboutTitle: "Mendorong Budaya Keselamatan & Pertumbuhan Bakat.",
            aboutDesc: "Seorang profesional HR dan Pelatihan yang berdedikasi dengan latar belakang kuat dalam pelatihan sistem keselamatan di industri pertambangan batu bara. Saya berspesialisasi dalam mengembangkan dan memberikan program pelatihan yang berfokus pada keselamatan yang mendukung Praktik Penambangan yang Baik dan meningkatkan efisiensi operasional. Terampil dalam proses orientasi, pengembangan kompetensi, audit internal SMKP, dan alat HR digital seperti LMS, Google Sheets, Power BI, dan PHP Laravel. Kemampuan yang terbukti untuk membangun kesadaran keselamatan, mendukung pengembangan tenaga kerja, dan mengoptimalkan sistem HR untuk mendorong kinerja dan kepatuhan.",
            whyHireTitle: "Mengapa Merekrut Saya?",
            whyHireSubTitle: "Perpaduan unik antara keahlian keselamatan, keterampilan pengembangan sumber daya manusia, dan digitalisasi sistem.",
            whyHireCard1Title: "Pendorong Budaya Keselamatan",
            whyHireCard1Desc: "Ahli dalam menerapkan standar SMKP dan mengembangkan program K3 yang menarik untuk mengurangi insiden dan membangun pola pikir proaktif yang mengutamakan keselamatan di semua tingkat operasional.",
            whyHireCard2Title: "Pengembang Talenta Terbukti",
            whyHireCard2Desc: "Berhasil merancang dan meluncurkan program berdampak tinggi seperti Program Kepemimpinan Muda (YLP) untuk membina pemimpin masa depan dan menutup kesenjangan kompetensi kritis.",
            whyHireCard3Title: "Pakar Digitalisasi HR",
            whyHireCard3Desc: "Terampil dalam membangun dan menerapkan alat HR digital, termasuk Learning Management Systems (LMS), untuk menyederhanakan proses dan meningkatkan efektivitas pelatihan.",
            servicesTitle: "Layanan & Keahlian",
            servicesSubTitle: "Berfokus pada pengembangan sumber daya manusia dan sistem keselamatan untuk mencapai keunggulan operasional.",
            serviceCard1Title: "Pelatihan & Induksi K3",
            serviceCard1Desc: "Mengembangkan modul pelatihan internal (JSA, HIRA-DC) dan induksi keselamatan berbasis SMKP.",
            serviceCard2Title: "Pengembangan SDM",
            serviceCard2Desc: "Merancang dan melaksanakan manajemen talenta, pengembangan karir, dan program kepemimpinan.",
            serviceCard3Title: "Pengembangan Sistem",
            serviceCard3Desc: "Membangun LMS berbasis web, kerangka kerja kompetensi, dan menerapkan sistem HR (SAP/ERP).",
            serviceCard4Title: "HR & Perekrutan",
            serviceCard4Desc: "Mengelola rekrutmen ujung-ke-ujung, orientasi, dan administrasi HR untuk kinerja optimal.",
            experienceTitle: "Perjalanan Karir Saya",
            experienceSubTitle: "Riwayat terperinci tentang peran dan pencapaian profesional saya.",
            exp1Title: "Kesehatan Keselamatan Lingkungan - Sistem, Pelatihan & Promosi",
            exp1Company: "PT Ganda Alam Makmur",
            exp1Date: "Des 2023 - Sekarang",
            exp1Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Mengembangkan dan menyampaikan modul pelatihan K3 internal: JSA, HIRA-DC, Investigasi, dan Komunikasi Keselamatan yang Efektif.</li><li>Memimpin induksi keselamatan bagi karyawan baru dan kontraktor, selaras dengan standar SMKP.</li><li>Mengoordinasikan audit internal untuk SMKP dan mendukung kesiapan audit ISO 45001 & 14001.</li><li><strong>Pencapaian:</strong> Mengurangi kesenjangan kompetensi dari 90% menjadi 40% dalam 4 bulan melalui pelatihan K3 yang ditargetkan.</li><li><strong>Pencapaian:</strong> Mencapai pengurangan konsumsi bahan bakar sebesar 15% untuk dump truck berkapasitas tinggi melalui ECU remapping.</li></ul>`,
            exp2Title: "Supervisor Sumber Daya Manusia",
            exp2Company: "PT Manoor Bulatn Lestari",
            exp2Date: "Ags 2023 - Des 2023",
            exp2Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Mengembangkan dan melaksanakan inisiatif manajemen talenta, pengembangan karir, dan manajemen perubahan.</li><li>Memimpin rekrutmen ujung-ke-ujung, dari peramalan kebutuhan hingga orientasi, dan memelopori digitalisasi proses.</li><li><strong>Pencapaian:</strong> Meluncurkan "YLP - Program Kepemimpinan Muda" untuk 24 lulusan baru dari universitas terkemuka.</li><li><strong>Pencapaian:</strong> Menciptakan Struktur Tingkat Pangkat dengan standar gaji dan jalur karir yang jelas.</li></ul>`,
            exp3Title: "Sumber Daya Manusia",
            exp3Company: "PT Satria Muda Prima",
            exp3Date: "Jan 2023 - Jun 2023",
            exp3Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Memimpin proses rekrutmen ujung-ke-ujung, termasuk perencanaan tenaga kerja, penyaringan CV, wawancara, dan penilaian psikologis.</li><li>Merancang dan menyampaikan program pelatihan orientasi dan melakukan Analisis Kebutuhan Pelatihan (TNA).</li><li>Mengelola kompensasi, tunjangan, dokumentasi HR, dan pelacakan kinerja karyawan.</li></ul>`,
            exp4Title: "Pemimpin Grup - Pelatihan, Pengembangan & Sistem",
            exp4Company: "PT Putra Perkasa Abadi",
            exp4Date: "Mar 2022 - Nov 2023",
            exp4Desc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Berperan sebagai pelatih untuk pelatihan GKM internal dan mengoordinasikan berbagai program pelatihan.</li><li>Membangun Sistem Manajemen Pembelajaran (LMS) berbasis web dengan modul, akun pengguna, dan penilaian.</li><li>Merumuskan kompetensi untuk setiap posisi dan membimbing program promosi dan orientasi untuk pekerja baru.</li></ul>`,
            testimonialsTitle: "Apa Kata Rekan Kerja Saya",
            testimonialsSubTitle: "Umpan balik dari para profesional yang pernah bekerja dengan saya.",
            testimonial1Text: `"Ahmad adalah seorang pengubah permainan. Kemampuannya untuk menerjemahkan peraturan keselamatan yang kompleks menjadi modul pelatihan yang praktis dan menarik secara signifikan meningkatkan kesadaran dan kinerja keselamatan tim kami."`,
            testimonial1Name: "Jane Doe",
            testimonial1Role: "Mantan Manajer, PT Ganda Alam Makmur",
            testimonial2Text: `"Program Kepemimpinan Muda yang diluncurkan Ahmad sangat transformatif. Dia memiliki bakat langka untuk mengidentifikasi potensi dan membangun sistem yang mendorong pertumbuhan dan kepemimpinan."`,
            testimonial2Name: "John Smith",
            testimonial2Role: "Direktur HR, PT Manoor Bulatn Lestari",
            portfolioTitle: "Inisiatif & Proyek Unggulan",
            portfolioSubTitle: "Inisiatif kunci untuk meningkatkan keselamatan, kompetensi, dan efisiensi.",
            project1Title: "Program Kepemimpinan Muda (YLP)",
            project1Category: "Pengembangan Bakat & Kepemimpinan",
            project2Title: "Area Uji Lapangan Praktis LV",
            project2Category: "Inisiatif Keselamatan",
            educationTitle: "Pendidikan",
            educationDegree: "Sarjana Manajemen",
            educationUniversity: "Universitas Islam Indonesia",
            educationDate: "2017 - 2021",
            educationDesc: `<ul class="mt-4 list-disc list-inside text-brand-text space-y-2"><li>Spesialisasi di bidang Manajemen Keuangan/Risiko, SDM, dan Operasi.</li><li>Juara 1 dalam kompetisi Business Model Canvas fakultas.</li></ul>`,
            certsTitle: "Sertifikasi Profesional",
            cert1Title: "Pelatih (TOT) KKNI Lvl 4",
            cert1Issuer: "BNSP",
            cert2Title: "Pengawas Operasional Pertama (POP)",
            cert2Issuer: "BNSP",
            cert3Title: "Implementasi SMKP",
            cert3Issuer: "PPSDM",
            cert4Title: "Staf Sumber Daya Manusia",
            cert4Issuer: "BNSP",
            cert5Title: "Six Sigma",
            cert5Issuer: "Pelatihan Online",
            contactTitle: "Mari Bangun Sesuatu yang Luar Biasa Bersama",
            contactBtn: "Mulai Percakapan",
            footerRole: "Profesional K3 & Pelatihan",
            footerLinksTitle: "Tautan Cepat",
            footerLinkAbout: "Tentang",
            footerLinkExperience: "Pengalaman",
            footerLinkPortfolio: "Portofolio",
            footerLinkContact: "Kontak",
            footerContactTitle: "Hubungi Saya",
            footerContactEmail: "Email: ahmadfaqihdidin@gmail.com",
            footerContactPhone: "Telepon: +62 821 4742 2821",
            footerContactLocation: "Lokasi: Semarang, Indonesia",
            footerMadeWith: "Dibuat dengan cinta & kode."
        }
    };

    window.currentLang = 'en'; // Default language, accessible globally

    function setLanguage(lang) {
        document.documentElement.lang = lang;
        document.querySelectorAll('[data-lang-key]').forEach(el => {
            const key = el.dataset.langKey;
            if (translations[lang] && translations[lang][key]) {
                el.innerHTML = translations[lang][key];
            }
        });
        window.currentLang = lang;
        document.getElementById('translate-button').textContent = lang === 'en' ? 'ID' : 'EN';
        document.getElementById('translate-button-mobile').textContent = lang === 'en' ? 'ID' : 'EN';
    }

    function handleTranslateClick() {
        const newLang = window.currentLang === 'en' ? 'id' : 'en';
        setLanguage(newLang);
    }

    document.getElementById('translate-button').addEventListener('click', handleTranslateClick);
    document.getElementById('translate-button-mobile').addEventListener('click', handleTranslateClick);

    // Set initial language
    setLanguage('en');
});
